[project]
name = "googleadklearn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=3.4.3",
    "requests>=2.32.4",
    "typing-extensions>=4.14.1",
]
